# Generated by Django 5.1.6 on 2025-04-15 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('role_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'solution_customizing.conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'user'), ('bot', 'bot')], max_length=4)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intent', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.BooleanField(default=False)),
                ('sql_query', models.TextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='solution_customizing_chatbot.conversation')),
            ],
            options={
                'db_table': 'solution_customizing.messages',
            },
        ),
    ]
