# Generated by Django 5.1.6 on 2025-04-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution_customizing_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
