# Generated by Django 5.1.6 on 2025-04-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_customizing_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePerm',
            fields=[
                ('role_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"admin"."roles_permission"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': '"admin"."users"',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False},
        ),
    ]
